# Generated by Django 4.2.7 on 2025-08-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_name", models.CharField(max_length=100, unique=True)),
                ("setting_value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="FaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encoding",
                    models.JSONField(help_text="Face encoding stored as JSON array"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Original face image", upload_to="face_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Quality score of the face encoding"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faces.person"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("recognized", "Recognized"),
                            ("unknown", "Unknown"),
                            ("multiple", "Multiple Faces"),
                            ("error", "Detection Error"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="Recognition confidence score", null=True
                    ),
                ),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
                (
                    "image_snapshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="detection_snapshots/"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the detection"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email alert was sent"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="faces.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-detection_time"],
            },
        ),
    ]
